default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

development:
  <<: *default
  database: loom_management_development

test:
  <<: *default
  database: loom_management_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "looma_db") %>
  ssl_mode: verify_identity
  sslca: /etc/ssl/cert.pem
